name: Continuous Integration

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    bun:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Cache Node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: bun-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: bun-

            - run: bun install
            - run: bun check
            - run: bun test
